### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by tomatobrown** [accesslint/accesslint.rb#20]
Maybe there just needs to be an update to the Readme file.  I'm just sure how to use this tool when the pages to be assessed require authentication.

**Comment by ckundo** [comment]
@tomatobrown thanks for the note! Please take a look at https://github.com/accesslint/accesslint.js. I've deprecated the Rubygem in favor of a simple javascript library, for a handful of reasons. With accesslint.js, you can conditionally include the javascript in test and development environments to get output.
